# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db7dc35dcd9da7ea0c59068da214033c487dc00e025914a5526b0d0d3f5bd5940c037fcb7f7d01ca597ebd799b267f5f3104c5658cd9a2b233adb8ad1e586df5

test:
  secret_key_base: 095a95f6206f0bd49dcf0bf6bc240a662b12454a12c8b4218e99dfb5c92dd8c76b90ad81912c989bcfe1cd3f72db6cac760b0d3577ba664c29e51cec04b6ce89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
